FROM node:22.2.0-alpine

WORKDIR /app

RUN mkdir -p /app/node_modules /tmp/.vite \
	&& chown -R node:node /app /tmp/.vite

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

CMD ["npm", "run", "dev", "--", "--host"]
