import type { SortableFieldsConfig } from '../decorators/sortable-fields.decorator';

export const SORTABLE_FIELDS = {
  usuarios: [
    'username',
    'email',
    'rol',
    'status',
    'activo',
    'createdAt',
    'updatedAt',
  ],
  recetas: [
    'nombre',
    'tiempoEstimadoMinutos',
    'tiempo',
    'tiempoPreparacion',
    'dificultad',
    'rendimiento',
    'costeUnitarioEstimado',
    'createdAt',
    'updatedAt',
  ],
  produccion: [
    'fechaProduccion',
    'fechaCaducidad',
    'fechaAgotado',
    'cantidadProducida',
    'costeTotalReal',
    'porcionesProducidas',
    'porcionesRestantes',
    'estado',
    'recetaNombre',
    'usuarioNombre',
    'createdAt',
    'updatedAt',
  ],
  recepciones: ['fechaRecepcion', 'estado', 'createdAt', 'updatedAt'],
  recepcionProductos: [
    'cantidadRecibida',
    'fechaRecepcion',
    'createdAt',
    'updatedAt',
  ],
  proveedores: [
    'nombre',
    'contacto',
    'telefono',
    'email',
    'direccion',
    'nif',
    'createdAt',
    'updatedAt',
  ],
  productos: [
    'nombre',
    'codigoBarras',
    'tipo',
    'marca',
    'createdAt',
    'updatedAt',
  ],
  pedidos: {
    fechaPedido: 'fechaPedido',
    fechaEntrega: 'fechaEntrega',
    costeTotal: 'costeTotal',
    estado: 'estado',
    fechaCreacion: 'createdAt',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
  },
  pedidoUsuarios: {
    fechaPedido: 'fechaPedido',
    fechaEntrega: 'fechaEntrega',
    costeTotal: 'costeTotal',
    estado: 'estado',
    numeroGlobal: 'numeroGlobal',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
  },
  purchaseBatches: [
    'createdAt',
    'updatedAt',
    'numeroGlobal',
    'estado',
    'referencia',
  ],
  movimientos: ['tipo', 'cantidad', 'entidad', 'createdAt'],
  movimientoHistorial: ['createdAt', 'cantidad'],
  mermas: ['createdAt', 'cantidad', 'motivo', 'productoId', 'usuarioId'],
  inventario: [
    'nombre',
    'cantidadActual',
    'cantidadMinima',
    'cantidadMaxima',
    'fechaEntrada',
    'fechaCaducidad',
    'createdAt',
    'updatedAt',
  ],
  incidencias: [
    'recepcionId',
    'pedidoId',
    'fechaResolucion',
    'createdAt',
    'updatedAt',
  ],
  incidenciasResueltas: ['fechaResolucion', 'createdAt', 'updatedAt'],
  albaranes: ['nAlbaran', 'concordancia', 'fecha', 'createdAt', 'updatedAt'],
  roles: [
    'nombre',
    'descripcion',
    'esSistema',
    'activo',
    'createdAt',
    'updatedAt',
  ],
  permisos: [
    'codigo',
    'nombre',
    'modulo',
    'accion',
    'activo',
    'createdAt',
    'updatedAt',
  ],
  preparaciones: [
    'recetaId',
    'usuarioId',
    'fechaProgramada',
    'fechaInicio',
    'fechaFinalizacion',
    'estado',
    'cantidadAProducir',
    'createdAt',
    'updatedAt',
  ],
} satisfies Record<string, SortableFieldsConfig>;
