FROM node:22.2.0-alpine

WORKDIR /app

# Install git for git config commands in logger
RUN apk add --no-cache git

RUN mkdir -p /app/node_modules /app/dist \
	&& chown -R node:node /app

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

CMD ["npm", "run", "start:dev"]
