import type { MassiveEndpointDefinition } from './massive-endpoints.constants';

/** Constantes públicas (MASSIVE_ENDPOINT_DEFINITIONS_ADDITIONAL) expuestas en smart-economat-backend (Nest). */
export const MASSIVE_ENDPOINT_DEFINITIONS_ADDITIONAL: readonly MassiveEndpointDefinition[] =
  [
    { method: 'POST', path: '/api/v1/admin/users/:id/force-reset' },
    { method: 'PATCH', path: '/api/v1/admin/users/:id/activate' },
    { method: 'DELETE', path: '/api/v1/albaranes/:id' },
    { method: 'POST', path: '/api/v1/albaranes/upload-documento' },
    { method: 'DELETE', path: '/api/v1/archivos/:id' },
    { method: 'POST', path: '/api/v1/archivos/upload' },
    { method: 'POST', path: '/api/v1/auth/register' },
    { method: 'POST', path: '/api/v1/auth/reset-password' },
    { method: 'DELETE', path: '/api/v1/historial-precio/:id' },
    { method: 'POST', path: '/api/v1/incidencias' },
    { method: 'PATCH', path: '/api/v1/incidencias/:id' },
    { method: 'DELETE', path: '/api/v1/incidencias/:id' },
    { method: 'POST', path: '/api/v1/incidencias/:id/resolver' },
    { method: 'POST', path: '/api/v1/incidencias/reportar' },
    { method: 'POST', path: '/api/v1/incidencias-resueltas' },
    { method: 'DELETE', path: '/api/v1/incidencias-resueltas/:id' },
    { method: 'DELETE', path: '/api/v1/inventario/:id' },
    { method: 'DELETE', path: '/api/v1/movimientos/:id' },
    { method: 'DELETE', path: '/api/v1/pedido/draft' },
    { method: 'DELETE', path: '/api/v1/pedidos/:id' },
    { method: 'POST', path: '/api/v1/preparaciones' },
    { method: 'DELETE', path: '/api/v1/preparaciones/:id' },
    { method: 'POST', path: '/api/v1/produccion/ejecutar' },
    { method: 'POST', path: '/api/v1/produccion/validar' },
    { method: 'DELETE', path: '/api/v1/productos/:id' },
    { method: 'DELETE', path: '/api/v1/profesores/admin-slots/:id' },
    { method: 'DELETE', path: '/api/v1/profesores/slots/:id' },
    { method: 'DELETE', path: '/api/v1/proveedor/:id' },
    { method: 'PATCH', path: '/api/v1/purchase-batches/:id/aceptar' },
    { method: 'PATCH', path: '/api/v1/purchase-batches/:id/cancelar' },
    { method: 'POST', path: '/api/v1/purchase-batches/consolidate' },
    { method: 'POST', path: '/api/v1/pedido-usuarios/from-missing-stock' },
    { method: 'POST', path: '/api/v1/pedido-usuarios/from-recipes' },
    { method: 'POST', path: '/api/v1/purchase-batches/from-missing-stock' },
    { method: 'POST', path: '/api/v1/recepcion-productos' },
    { method: 'DELETE', path: '/api/v1/recepcion-productos/:id' },
    { method: 'DELETE', path: '/api/v1/recepcion/draft' },
    { method: 'POST', path: '/api/v1/recepcion/draft' },
    { method: 'POST', path: '/api/v1/recepciones' },
    { method: 'POST', path: '/api/v1/recetas' },
    { method: 'DELETE', path: '/api/v1/recetas/:id' },
    { method: 'POST', path: '/api/v1/recetas/:id/cocinar' },
    { method: 'POST', path: '/api/v1/recetas/:id/recalcular-costes' },
    { method: 'DELETE', path: '/api/v1/ubicacion/:id' },
    { method: 'DELETE', path: '/api/v1/usuarios/:id' },
    { method: 'PATCH', path: '/api/v1/usuarios/:id/activar' },
    { method: 'PATCH', path: '/api/v1/usuarios/:id/admin' },
    { method: 'POST', path: '/api/v1/usuarios/admin' },
  ];
